# -*- coding: utf-8 -*-
"""codeAlpha_Task1_Hangman_Game.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FvUrUk1AfZ7tPr6iJO_iiNLBy5_N_mf
"""

import random

word_list = ["python","cloud","laptop","coading","intern"]

word = random.choice(word_list)
guessed_letters = []
incorrect_guesses = 0
max_guesses = 6

print("Welcome to Hagman Game")

while incorrect_guesses < max_guesses:
      display_word = ""

      for letter in word:
          if letter in guessed_letters:
              display_word += letter +" "
          else:
              display_word += "_ "

      print("\nWord:",display_word)

      if "_ "  not in display_word:
          print("Congratulations! You guessed the word:", word)
          break

      guess = input("Guess a letter:").lower()

      if len(guess) != 1 or not guess.isalpha():
          print("Please enter only one alphabet.")
          continue

      if guess in guessed_letters:
          print("You already guessed that letter.")
          continue

      guessed_letters.append(guess)

      if guess in word:
          print("Correct!")
      else:
          incorrect_guesses += 1
          print("Wrong guess!")
          print("Remaining chances:", max_guesses - incorrect_guesses)

      if incorrect_guesses == max_guesses:
        print("\n X Game Over !")
        print("The correct word was:", word)