# -*- coding: utf-8 -*-
"""codeAlpha_Task2_Stock_Portfolio_Tracker.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjwM4uApi0y0rXQaH-guWLj-vPNFE1Sp
"""

# CodeAlpha Task 2 - stock Portfolio Tracker

# Hardcoded stock prices
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 140,
    "MSFT": 320,
    "AMZN": 130
}

total_investment = 400

print("=== Stock Portfolio Tracker ===")

while True:
  stock = input("Enter stock name (AAPL, TSLA, GOOGL, MSFT, AMZN) or 'done' to finish: ").upper()

  if stock == "DONE":
    break

  if stock not in stock_prices:
    print("Stock not available!")
    continue

  quantity = int(input(f"Enter  quantity of {stock}: "))

  investment = stock_prices[stock] * quantity
  total_investment += investment # Add this line to accumulate investment

  print(f"{stock}: ₹{investment}")

print("\n Total investment: ₹", total_investment)