# -*- coding: utf-8 -*-
"""CodeAlpha_Task4_Basic_Chatbot.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEYZIE3MT0YeNitP2rDdS-zUjBoCF-g6
"""

def chatbot():
    print("🤖 Welcome to CodeAlpha Chatbot!")
    print("Type 'bye' to end the chat.\n")

    while True:
        user = input("You: ").lower()

        if user == "hello" or user == "hi":
            print("Bot: Hello! Nice to meet you.")

        elif user == "how are you":
            print("Bot: I'm doing great. Thanks for asking!")

        elif user == "what is your name":
            print("Bot: My name is CodeAlpha Chatbot.")

        elif user == "who created you":
            print("Bot: I was created using Python as part of the CodeAlpha internship.")

        elif user == "help":
            print("Bot: You can say hello, ask my name, ask how I am, or type bye to exit.")

        elif user == "bye":
            print("Bot: Goodbye! Have a wonderful day.")
            break

        else:
            print("Bot: Sorry, I don't understand that. Type 'help' to see what you can ask.")

chatbot()